version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/email_tracker
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    volumes:
      - .:/app
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=email_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A main.celery worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/email_tracker
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A main.celery beat --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/email_tracker
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data: