"""add_user_settings_table

Revision ID: 4ee9c3d1d35a
Revises: b54e3a8fd87c
Create Date: 2025-08-14 18:49:01.257427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee9c3d1d35a'
down_revision: Union[str, None] = 'b54e3a8fd87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('smtp_settings', sa.Text(), nullable=True),
    sa.Column('company_settings', sa.Text(), nullable=True),
    sa.Column('security_settings', sa.Text(), nullable=True),
    sa.Column('notification_settings', sa.Text(), nullable=True),
    sa.Column('storage_settings', sa.Text(), nullable=True),
    sa.Column('domain_settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_user_settings_updated_at', 'user_settings', ['updated_at'], unique=False)
    op.create_index('idx_user_settings_user_id', 'user_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_settings_user_id', table_name='user_settings')
    op.drop_index('idx_user_settings_updated_at', table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
