"""add_template_folders_table

Revision ID: 6a054832e6dc
Revises: d26f0b9210e4
Create Date: 2025-08-12 18:55:01.846953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a054832e6dc'
down_revision: Union[str, None] = 'd26f0b9210e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['template_folders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', 'parent_id', name='uq_user_folder_name')
    )
    op.create_index('idx_folder_name', 'template_folders', ['user_id', 'name'], unique=False)
    op.create_index('idx_folder_parent', 'template_folders', ['parent_id'], unique=False)
    op.create_index('idx_folder_user', 'template_folders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_folder_user', table_name='template_folders')
    op.drop_index('idx_folder_parent', table_name='template_folders')
    op.drop_index('idx_folder_name', table_name='template_folders')
    op.drop_table('template_folders')
    # ### end Alembic commands ###
