"""Add tags column to campaigns table

Revision ID: ac8130488348
Revises: add_security_models_2025
Create Date: 2025-08-18 21:40:08.198831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ac8130488348'
down_revision: Union[str, None] = 'add_security_models_2025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_security_audit_action', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_created_at', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_ip_address', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_success', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_user_id', table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index('idx_usage_log_date', table_name='feature_usage_logs')
    op.drop_index('idx_usage_log_feature', table_name='feature_usage_logs')
    op.drop_index('idx_usage_log_subscription', table_name='feature_usage_logs')
    op.drop_index('idx_usage_log_user', table_name='feature_usage_logs')
    op.drop_index('idx_usage_log_user_feature_date', table_name='feature_usage_logs')
    op.drop_table('feature_usage_logs')
    op.drop_index('idx_subscription_plan_active', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_name', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_sort', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index('idx_security_settings_user_id', table_name='security_settings')
    op.drop_table('security_settings')
    op.drop_index('idx_user_subscription_period_end', table_name='user_subscriptions')
    op.drop_index('idx_user_subscription_plan_id', table_name='user_subscriptions')
    op.drop_index('idx_user_subscription_status', table_name='user_subscriptions')
    op.drop_index('idx_user_subscription_user_id', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_table('password_reset_tokens')
    op.add_column('campaigns', sa.Column('tags', sa.Text(), nullable=True))
    op.alter_column('campaigns', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index('idx_performance_user_campaigns', table_name='campaigns')
    op.drop_index('idx_performance_user_analytics', table_name='email_trackers')
    op.create_index('idx_password_reset_token', 'password_resets', ['token_hash'], unique=False)
    op.create_index('idx_password_reset_user_id', 'password_resets', ['user_id'], unique=False)
    op.alter_column('templates', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('templates', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('templates', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('templates', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('templates', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'thumbnail_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'folder',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'locked_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'parent_template_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'templates', 'template_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.alter_column('templates', 'parent_template_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'locked_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'folder',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'thumbnail_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('templates', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('templates', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('templates', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index('idx_password_reset_user_id', table_name='password_resets')
    op.drop_index('idx_password_reset_token', table_name='password_resets')
    op.create_index('idx_performance_user_analytics', 'email_trackers', ['user_id', 'created_at', 'delivered'], unique=False)
    op.create_index('idx_performance_user_campaigns', 'campaigns', ['user_id', 'status', 'created_at'], unique=False)
    op.alter_column('campaigns', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('campaigns', 'tags')
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('user_subscriptions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('plan_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('current_period_start', sa.DATETIME(), nullable=False),
    sa.Column('current_period_end', sa.DATETIME(), nullable=False),
    sa.Column('campaigns_used', sa.INTEGER(), nullable=True),
    sa.Column('emails_sent_this_month', sa.INTEGER(), nullable=True),
    sa.Column('templates_used', sa.INTEGER(), nullable=True),
    sa.Column('contacts_count', sa.INTEGER(), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), nullable=True),
    sa.Column('trial_start', sa.DATETIME(), nullable=True),
    sa.Column('trial_end', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uix_user_subscription')
    )
    op.create_index('idx_user_subscription_user_id', 'user_subscriptions', ['user_id'], unique=False)
    op.create_index('idx_user_subscription_status', 'user_subscriptions', ['status'], unique=False)
    op.create_index('idx_user_subscription_plan_id', 'user_subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_user_subscription_period_end', 'user_subscriptions', ['current_period_end'], unique=False)
    op.create_table('security_settings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('login_notifications', sa.BOOLEAN(), nullable=True),
    sa.Column('suspicious_activity_alerts', sa.BOOLEAN(), nullable=True),
    sa.Column('session_timeout_hours', sa.INTEGER(), nullable=True),
    sa.Column('max_concurrent_sessions', sa.INTEGER(), nullable=True),
    sa.Column('api_key_rotation_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('api_key_rotation_days', sa.INTEGER(), nullable=True),
    sa.Column('require_password_change', sa.BOOLEAN(), nullable=True),
    sa.Column('password_change_days', sa.INTEGER(), nullable=True),
    sa.Column('last_password_change', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_security_settings_user_id', 'security_settings', ['user_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('billing_interval', sa.VARCHAR(), nullable=False),
    sa.Column('max_campaigns', sa.INTEGER(), nullable=True),
    sa.Column('max_recipients_per_campaign', sa.INTEGER(), nullable=True),
    sa.Column('max_monthly_emails', sa.INTEGER(), nullable=True),
    sa.Column('max_templates', sa.INTEGER(), nullable=True),
    sa.Column('max_contacts', sa.INTEGER(), nullable=True),
    sa.Column('features', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_popular', sa.BOOLEAN(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_subscription_plan_sort', 'subscription_plans', ['sort_order'], unique=False)
    op.create_index('idx_subscription_plan_name', 'subscription_plans', ['name'], unique=False)
    op.create_index('idx_subscription_plan_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_table('feature_usage_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('subscription_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('feature_name', sa.VARCHAR(), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('usage_date', sa.DATETIME(), nullable=True),
    sa.Column('feature_metadata', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_log_user_feature_date', 'feature_usage_logs', ['user_id', 'feature_name', 'usage_date'], unique=False)
    op.create_index('idx_usage_log_user', 'feature_usage_logs', ['user_id'], unique=False)
    op.create_index('idx_usage_log_subscription', 'feature_usage_logs', ['subscription_id'], unique=False)
    op.create_index('idx_usage_log_feature', 'feature_usage_logs', ['feature_name'], unique=False)
    op.create_index('idx_usage_log_date', 'feature_usage_logs', ['usage_date'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), nullable=True),
    sa.Column('resource_id', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('failure_reason', sa.TEXT(), nullable=True),
    sa.Column('security_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_security_audit_user_id', 'security_audit_logs', ['user_id'], unique=False)
    op.create_index('idx_security_audit_success', 'security_audit_logs', ['success'], unique=False)
    op.create_index('idx_security_audit_ip_address', 'security_audit_logs', ['ip_address'], unique=False)
    op.create_index('idx_security_audit_created_at', 'security_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_security_audit_action', 'security_audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
