"""Add two factor authentication tables

Revision ID: b54e3a8fd87c
Revises: 6bf0eb9438e9
Create Date: 2025-08-14 16:42:56.637413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54e3a8fd87c'
down_revision: Union[str, None] = '6bf0eb9438e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('two_factor_auth',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('backup_codes_hash', sa.Text(), nullable=True),
    sa.Column('backup_codes_used', sa.Text(), nullable=True),
    sa.Column('qr_code_generated_at', sa.DateTime(), nullable=True),
    sa.Column('setup_completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_code_used', sa.String(), nullable=True),
    sa.Column('recovery_codes_generated_at', sa.DateTime(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_2fa_enabled', 'two_factor_auth', ['is_enabled'], unique=False)
    op.create_index('idx_2fa_user_id', 'two_factor_auth', ['user_id'], unique=False)
    op.create_index('idx_2fa_verified', 'two_factor_auth', ['is_verified'], unique=False)
    op.create_table('two_factor_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_consumed', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('idx_2fa_session_expires_at', 'two_factor_sessions', ['expires_at'], unique=False)
    op.create_index('idx_2fa_session_purpose', 'two_factor_sessions', ['purpose'], unique=False)
    op.create_index('idx_2fa_session_token', 'two_factor_sessions', ['session_token'], unique=False)
    op.create_index('idx_2fa_session_user_id', 'two_factor_sessions', ['user_id'], unique=False)
    op.create_table('two_factor_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('two_factor_auth_id', sa.String(), nullable=False),
    sa.Column('code_type', sa.String(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['two_factor_auth_id'], ['two_factor_auth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_2fa_attempt_2fa_id', 'two_factor_attempts', ['two_factor_auth_id'], unique=False)
    op.create_index('idx_2fa_attempt_attempted_at', 'two_factor_attempts', ['attempted_at'], unique=False)
    op.create_index('idx_2fa_attempt_ip', 'two_factor_attempts', ['ip_address'], unique=False)
    op.create_index('idx_2fa_attempt_success', 'two_factor_attempts', ['success'], unique=False)
    op.drop_index('idx_performance_user_campaigns', table_name='campaigns')
    op.drop_index('idx_performance_user_analytics', table_name='email_trackers')
    op.alter_column('templates', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('templates', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('templates', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('templates', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('templates', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'thumbnail_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'folder',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'locked_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'parent_template_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'templates', 'template_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.alter_column('templates', 'parent_template_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'locked_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'folder',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'thumbnail_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('templates', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('templates', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('templates', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.create_index('idx_performance_user_analytics', 'email_trackers', ['user_id', 'created_at', 'delivered'], unique=False)
    op.create_index('idx_performance_user_campaigns', 'campaigns', ['user_id', 'status', 'created_at'], unique=False)
    op.drop_index('idx_2fa_attempt_success', table_name='two_factor_attempts')
    op.drop_index('idx_2fa_attempt_ip', table_name='two_factor_attempts')
    op.drop_index('idx_2fa_attempt_attempted_at', table_name='two_factor_attempts')
    op.drop_index('idx_2fa_attempt_2fa_id', table_name='two_factor_attempts')
    op.drop_table('two_factor_attempts')
    op.drop_index('idx_2fa_session_user_id', table_name='two_factor_sessions')
    op.drop_index('idx_2fa_session_token', table_name='two_factor_sessions')
    op.drop_index('idx_2fa_session_purpose', table_name='two_factor_sessions')
    op.drop_index('idx_2fa_session_expires_at', table_name='two_factor_sessions')
    op.drop_table('two_factor_sessions')
    op.drop_index('idx_2fa_verified', table_name='two_factor_auth')
    op.drop_index('idx_2fa_user_id', table_name='two_factor_auth')
    op.drop_index('idx_2fa_enabled', table_name='two_factor_auth')
    op.drop_table('two_factor_auth')
    # ### end Alembic commands ###
