"""Add unified campaign schema with send_type and recurring parent_child tracking

Revision ID: c8ad14760adf
Revises: 7bcd3e391bc1
Create Date: 2025-08-20 16:43:18.301428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c8ad14760adf'
down_revision: Union[str, None] = '7bcd3e391bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_security_audit_action', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_created_at', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_ip_address', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_success', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_user_id', table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    op.drop_index('idx_global_defaults_active', table_name='global_defaults')
    op.drop_index('idx_global_defaults_category', table_name='global_defaults')
    op.drop_index('idx_global_defaults_category_key', table_name='global_defaults')
    op.drop_table('global_defaults')
    op.drop_index('idx_user_defaults_active', table_name='user_defaults')
    op.drop_index('idx_user_defaults_category', table_name='user_defaults')
    op.drop_index('idx_user_defaults_tenant', table_name='user_defaults')
    op.drop_index('idx_user_defaults_user', table_name='user_defaults')
    op.drop_index('idx_user_defaults_user_category', table_name='user_defaults')
    op.drop_table('user_defaults')
    op.drop_index('idx_security_settings_user_id', table_name='security_settings')
    op.drop_table('security_settings')
    op.drop_index('idx_password_reset_expires_at', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_token_hash', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_user_id', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_usage_log_date', table_name='feature_usage_logs')
    op.drop_index('idx_usage_log_feature', table_name='feature_usage_logs')
    op.drop_index('idx_usage_log_subscription', table_name='feature_usage_logs')
    op.drop_index('idx_usage_log_user', table_name='feature_usage_logs')
    op.drop_index('idx_usage_log_user_feature_date', table_name='feature_usage_logs')
    op.drop_table('feature_usage_logs')
    op.drop_index('idx_tenant_defaults_active', table_name='tenant_defaults')
    op.drop_index('idx_tenant_defaults_category', table_name='tenant_defaults')
    op.drop_index('idx_tenant_defaults_tenant', table_name='tenant_defaults')
    op.drop_index('idx_tenant_defaults_tenant_category', table_name='tenant_defaults')
    op.drop_table('tenant_defaults')
    op.drop_index('idx_user_subscription_period_end', table_name='user_subscriptions')
    op.drop_index('idx_user_subscription_plan_id', table_name='user_subscriptions')
    op.drop_index('idx_user_subscription_status', table_name='user_subscriptions')
    op.drop_index('idx_user_subscription_user_id', table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index('idx_subscription_plan_active', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_name', table_name='subscription_plans')
    op.drop_index('idx_subscription_plan_sort', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.add_column('campaigns', sa.Column('send_type', sa.String(length=20), nullable=True, server_default='immediate'))
    # Update existing campaigns to have immediate send_type
    op.execute("UPDATE campaigns SET send_type = 'immediate' WHERE send_type IS NULL")
    # Make the column NOT NULL after populating it
    op.alter_column('campaigns', 'send_type', nullable=False)
    op.add_column('campaigns', sa.Column('parent_campaign_id', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('recurring_campaign_id', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('sequence_number', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('next_send_at', sa.DateTime(), nullable=True))
    op.alter_column('campaigns', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index('idx_performance_user_campaigns', table_name='campaigns')
    op.create_index('idx_campaign_next_send', 'campaigns', ['next_send_at'], unique=False)
    op.create_index('idx_campaign_parent_id', 'campaigns', ['parent_campaign_id'], unique=False)
    op.create_index('idx_campaign_recurring_id', 'campaigns', ['recurring_campaign_id'], unique=False)
    op.create_index('idx_campaign_send_type', 'campaigns', ['send_type'], unique=False)
    op.create_index('idx_campaign_sequence', 'campaigns', ['parent_campaign_id', 'sequence_number'], unique=False)
    op.create_foreign_key(None, 'campaigns', 'campaigns', ['parent_campaign_id'], ['id'])
    op.drop_index('idx_performance_user_analytics', table_name='email_trackers')
    op.create_index('idx_password_reset_expires_at', 'password_resets', ['expires_at'], unique=False)
    op.create_index('idx_password_reset_token', 'password_resets', ['token_hash'], unique=False)
    op.create_index('idx_password_reset_user_id', 'password_resets', ['user_id'], unique=False)
    op.add_column('recurring_campaign_occurrences', sa.Column('user_id', sa.String(), nullable=True))
    # Update existing occurrences to have user_id from their recurring campaign
    op.execute("""UPDATE recurring_campaign_occurrences 
                  SET user_id = (SELECT user_id FROM recurring_campaigns 
                               WHERE recurring_campaigns.id = recurring_campaign_occurrences.recurring_campaign_id)
                  WHERE user_id IS NULL""")
    # Make the column NOT NULL after populating it
    op.alter_column('recurring_campaign_occurrences', 'user_id', nullable=False)
    op.add_column('recurring_campaign_occurrences', sa.Column('actual_sent_at', sa.DateTime(), nullable=True))
    op.add_column('recurring_campaign_occurrences', sa.Column('recipients_snapshot', sa.Text(), nullable=True))
    op.alter_column('recurring_campaign_occurrences', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('recurring_campaign_occurrences', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('idx_recurring_occurrences_campaign', table_name='recurring_campaign_occurrences')
    op.drop_index('idx_recurring_occurrences_schedule', table_name='recurring_campaign_occurrences')
    op.drop_index('idx_recurring_occurrences_status', table_name='recurring_campaign_occurrences')
    op.drop_constraint(None, 'recurring_campaign_occurrences', type_='foreignkey')
    op.drop_constraint(None, 'recurring_campaign_occurrences', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_campaign_occurrences', 'recurring_campaigns', ['recurring_campaign_id'], ['id'])
    op.create_foreign_key(None, 'recurring_campaign_occurrences', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'recurring_campaign_occurrences', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('recurring_campaign_occurrences', 'retry_count')
    op.drop_column('recurring_campaign_occurrences', 'next_retry_at')
    op.drop_column('recurring_campaign_occurrences', 'sent_at')
    op.drop_column('recurring_campaign_occurrences', 'emails_unsubscribed')
    op.add_column('recurring_campaigns', sa.Column('subject_template', sa.String(), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('monthly_day', sa.Integer(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('monthly_week', sa.Integer(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('monthly_weekday', sa.Enum('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY', name='weekday'), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('recipient_list_id', sa.String(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('segment_id', sa.String(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('dynamic_recipients', sa.Boolean(), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('html_template', sa.Text(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('text_template', sa.Text(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('auto_generate_text', sa.Boolean(), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('total_scheduled', sa.Integer(), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('total_sent', sa.Integer(), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('total_failed', sa.Integer(), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('send_rate_limit', sa.Integer(), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('personalization_fields', sa.Text(), nullable=True))
    op.alter_column('recurring_campaigns', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('recurring_campaigns', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('idx_recurring_campaigns_active', table_name='recurring_campaigns')
    op.drop_index('idx_recurring_campaigns_next_send', table_name='recurring_campaigns')
    op.drop_index('idx_recurring_campaigns_user_status', table_name='recurring_campaigns')
    op.drop_constraint(None, 'recurring_campaigns', type_='foreignkey')
    op.drop_constraint(None, 'recurring_campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_campaigns', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'recurring_campaigns', 'users', ['user_id'], ['id'])
    op.drop_column('recurring_campaigns', 'email_html')
    op.drop_column('recurring_campaigns', 'cancelled_at')
    op.drop_column('recurring_campaigns', 'total_occurrences')
    op.drop_column('recurring_campaigns', 'email_text')
    op.drop_column('recurring_campaigns', 'subject')
    op.drop_column('recurring_campaigns', 'paused_at')
    op.drop_column('recurring_campaigns', 'contact_list_ids')
    op.alter_column('templates', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('templates', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('templates', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('templates', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('templates', 'subject',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'thumbnail_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'folder',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'locked_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('templates', 'parent_template_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'templates', 'template_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.alter_column('templates', 'parent_template_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'locked_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'folder',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'thumbnail_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'subject',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'draft'"))
    op.alter_column('templates', 'type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('templates', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('templates', 'user_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('templates', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('recurring_campaigns', sa.Column('contact_list_ids', sa.TEXT(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('paused_at', sa.DATETIME(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('subject', sa.VARCHAR(), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('email_text', sa.TEXT(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('total_occurrences', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('recurring_campaigns', sa.Column('cancelled_at', sa.DATETIME(), nullable=True))
    op.add_column('recurring_campaigns', sa.Column('email_html', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'recurring_campaigns', type_='foreignkey')
    op.drop_constraint(None, 'recurring_campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_campaigns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recurring_campaigns', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_recurring_campaigns_user_status', 'recurring_campaigns', ['user_id', 'status'], unique=False)
    op.create_index('idx_recurring_campaigns_next_send', 'recurring_campaigns', ['next_send_at'], unique=False)
    op.create_index('idx_recurring_campaigns_active', 'recurring_campaigns', ['is_active', 'next_send_at'], unique=False)
    op.alter_column('recurring_campaigns', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('recurring_campaigns', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('recurring_campaigns', 'personalization_fields')
    op.drop_column('recurring_campaigns', 'send_rate_limit')
    op.drop_column('recurring_campaigns', 'total_failed')
    op.drop_column('recurring_campaigns', 'total_sent')
    op.drop_column('recurring_campaigns', 'total_scheduled')
    op.drop_column('recurring_campaigns', 'auto_generate_text')
    op.drop_column('recurring_campaigns', 'text_template')
    op.drop_column('recurring_campaigns', 'html_template')
    op.drop_column('recurring_campaigns', 'dynamic_recipients')
    op.drop_column('recurring_campaigns', 'segment_id')
    op.drop_column('recurring_campaigns', 'recipient_list_id')
    op.drop_column('recurring_campaigns', 'monthly_weekday')
    op.drop_column('recurring_campaigns', 'monthly_week')
    op.drop_column('recurring_campaigns', 'monthly_day')
    op.drop_column('recurring_campaigns', 'subject_template')
    op.add_column('recurring_campaign_occurrences', sa.Column('emails_unsubscribed', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
    op.add_column('recurring_campaign_occurrences', sa.Column('sent_at', sa.DATETIME(), nullable=True))
    op.add_column('recurring_campaign_occurrences', sa.Column('next_retry_at', sa.DATETIME(), nullable=True))
    op.add_column('recurring_campaign_occurrences', sa.Column('retry_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
    op.drop_constraint(None, 'recurring_campaign_occurrences', type_='foreignkey')
    op.drop_constraint(None, 'recurring_campaign_occurrences', type_='foreignkey')
    op.drop_constraint(None, 'recurring_campaign_occurrences', type_='foreignkey')
    op.create_foreign_key(None, 'recurring_campaign_occurrences', 'recurring_campaigns', ['recurring_campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'recurring_campaign_occurrences', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_recurring_occurrences_status', 'recurring_campaign_occurrences', ['status', 'scheduled_at'], unique=False)
    op.create_index('idx_recurring_occurrences_schedule', 'recurring_campaign_occurrences', ['scheduled_at', 'status'], unique=False)
    op.create_index('idx_recurring_occurrences_campaign', 'recurring_campaign_occurrences', ['recurring_campaign_id'], unique=False)
    op.alter_column('recurring_campaign_occurrences', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('recurring_campaign_occurrences', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('recurring_campaign_occurrences', 'recipients_snapshot')
    op.drop_column('recurring_campaign_occurrences', 'actual_sent_at')
    op.drop_column('recurring_campaign_occurrences', 'user_id')
    op.drop_index('idx_password_reset_user_id', table_name='password_resets')
    op.drop_index('idx_password_reset_token', table_name='password_resets')
    op.drop_index('idx_password_reset_expires_at', table_name='password_resets')
    op.create_index('idx_performance_user_analytics', 'email_trackers', ['user_id', 'created_at', 'delivered'], unique=False)
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_index('idx_campaign_sequence', table_name='campaigns')
    op.drop_index('idx_campaign_send_type', table_name='campaigns')
    op.drop_index('idx_campaign_recurring_id', table_name='campaigns')
    op.drop_index('idx_campaign_parent_id', table_name='campaigns')
    op.drop_index('idx_campaign_next_send', table_name='campaigns')
    op.create_index('idx_performance_user_campaigns', 'campaigns', ['user_id', 'status', 'created_at'], unique=False)
    op.alter_column('campaigns', 'current_step',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_column('campaigns', 'next_send_at')
    op.drop_column('campaigns', 'sequence_number')
    op.drop_column('campaigns', 'recurring_campaign_id')
    op.drop_column('campaigns', 'parent_campaign_id')
    op.drop_column('campaigns', 'send_type')
    op.create_table('subscription_plans',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('display_name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('billing_interval', sa.VARCHAR(), nullable=False),
    sa.Column('max_campaigns', sa.INTEGER(), nullable=True),
    sa.Column('max_recipients_per_campaign', sa.INTEGER(), nullable=True),
    sa.Column('max_monthly_emails', sa.INTEGER(), nullable=True),
    sa.Column('max_templates', sa.INTEGER(), nullable=True),
    sa.Column('max_contacts', sa.INTEGER(), nullable=True),
    sa.Column('features', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_popular', sa.BOOLEAN(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_subscription_plan_sort', 'subscription_plans', ['sort_order'], unique=False)
    op.create_index('idx_subscription_plan_name', 'subscription_plans', ['name'], unique=False)
    op.create_index('idx_subscription_plan_active', 'subscription_plans', ['is_active'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('plan_id', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('current_period_start', sa.DATETIME(), nullable=False),
    sa.Column('current_period_end', sa.DATETIME(), nullable=False),
    sa.Column('campaigns_used', sa.INTEGER(), nullable=True),
    sa.Column('emails_sent_this_month', sa.INTEGER(), nullable=True),
    sa.Column('templates_used', sa.INTEGER(), nullable=True),
    sa.Column('contacts_count', sa.INTEGER(), nullable=True),
    sa.Column('stripe_subscription_id', sa.VARCHAR(), nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(), nullable=True),
    sa.Column('cancel_at_period_end', sa.BOOLEAN(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), nullable=True),
    sa.Column('trial_start', sa.DATETIME(), nullable=True),
    sa.Column('trial_end', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uix_user_subscription')
    )
    op.create_index('idx_user_subscription_user_id', 'user_subscriptions', ['user_id'], unique=False)
    op.create_index('idx_user_subscription_status', 'user_subscriptions', ['status'], unique=False)
    op.create_index('idx_user_subscription_plan_id', 'user_subscriptions', ['plan_id'], unique=False)
    op.create_index('idx_user_subscription_period_end', 'user_subscriptions', ['current_period_end'], unique=False)
    op.create_table('tenant_defaults',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('key', sa.VARCHAR(length=200), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('value_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'category', 'key', name='_tenant_defaults_tenant_category_key')
    )
    op.create_index('idx_tenant_defaults_tenant_category', 'tenant_defaults', ['tenant_id', 'category'], unique=False)
    op.create_index('idx_tenant_defaults_tenant', 'tenant_defaults', ['tenant_id'], unique=False)
    op.create_index('idx_tenant_defaults_category', 'tenant_defaults', ['category'], unique=False)
    op.create_index('idx_tenant_defaults_active', 'tenant_defaults', ['is_active'], unique=False)
    op.create_table('feature_usage_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('subscription_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('feature_name', sa.VARCHAR(), nullable=False),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.Column('usage_date', sa.DATETIME(), nullable=True),
    sa.Column('feature_metadata', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['user_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_log_user_feature_date', 'feature_usage_logs', ['user_id', 'feature_name', 'usage_date'], unique=False)
    op.create_index('idx_usage_log_user', 'feature_usage_logs', ['user_id'], unique=False)
    op.create_index('idx_usage_log_subscription', 'feature_usage_logs', ['subscription_id'], unique=False)
    op.create_index('idx_usage_log_feature', 'feature_usage_logs', ['feature_name'], unique=False)
    op.create_index('idx_usage_log_date', 'feature_usage_logs', ['usage_date'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('token', sa.VARCHAR(), nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_password_reset_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('idx_password_reset_token_hash', 'password_reset_tokens', ['token_hash'], unique=False)
    op.create_index('idx_password_reset_expires_at', 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_table('security_settings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('login_notifications', sa.BOOLEAN(), nullable=True),
    sa.Column('suspicious_activity_alerts', sa.BOOLEAN(), nullable=True),
    sa.Column('session_timeout_hours', sa.INTEGER(), nullable=True),
    sa.Column('max_concurrent_sessions', sa.INTEGER(), nullable=True),
    sa.Column('api_key_rotation_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('api_key_rotation_days', sa.INTEGER(), nullable=True),
    sa.Column('require_password_change', sa.BOOLEAN(), nullable=True),
    sa.Column('password_change_days', sa.INTEGER(), nullable=True),
    sa.Column('last_password_change', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('idx_security_settings_user_id', 'security_settings', ['user_id'], unique=False)
    op.create_table('user_defaults',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('key', sa.VARCHAR(length=200), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('value_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'key', name='_user_defaults_user_category_key')
    )
    op.create_index('idx_user_defaults_user_category', 'user_defaults', ['user_id', 'category'], unique=False)
    op.create_index('idx_user_defaults_user', 'user_defaults', ['user_id'], unique=False)
    op.create_index('idx_user_defaults_tenant', 'user_defaults', ['tenant_id'], unique=False)
    op.create_index('idx_user_defaults_category', 'user_defaults', ['category'], unique=False)
    op.create_index('idx_user_defaults_active', 'user_defaults', ['is_active'], unique=False)
    op.create_table('global_defaults',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('key', sa.VARCHAR(length=200), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=False),
    sa.Column('value_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'key', name='_global_defaults_category_key')
    )
    op.create_index('idx_global_defaults_category_key', 'global_defaults', ['category', 'key'], unique=False)
    op.create_index('idx_global_defaults_category', 'global_defaults', ['category'], unique=False)
    op.create_index('idx_global_defaults_active', 'global_defaults', ['is_active'], unique=False)
    op.create_table('security_audit_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), nullable=True),
    sa.Column('resource_id', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('success', sa.BOOLEAN(), nullable=False),
    sa.Column('failure_reason', sa.TEXT(), nullable=True),
    sa.Column('security_metadata', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_security_audit_user_id', 'security_audit_logs', ['user_id'], unique=False)
    op.create_index('idx_security_audit_success', 'security_audit_logs', ['success'], unique=False)
    op.create_index('idx_security_audit_ip_address', 'security_audit_logs', ['ip_address'], unique=False)
    op.create_index('idx_security_audit_created_at', 'security_audit_logs', ['created_at'], unique=False)
    op.create_index('idx_security_audit_action', 'security_audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
