"""Add user management tables

Revision ID: d26f0b9210e4
Revises: 
Create Date: 2025-07-29 23:55:02.411897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd26f0b9210e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_api_key_user_id', 'api_keys', ['user_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index('idx_api_key_user_id', table_name='api_keys')
    # ### end Alembic commands ###
